# Generated by Django 5.0.4 on 2024-04-17 13:07

from django.db import migrations
from django.contrib.auth.models import Group, Permission

def create_groups_and_permissions(apps, schema_editor):
    # Create Groups
    client_group, created = Group.objects.get_or_create(name='Cliente')

    # asignar permisos
    view_user_permission = Permission.objects.get(codename='view_customuser')
    client_group.permissions.add(view_user_permission)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups_and_permissions),
    ]
